name: passwordless

services:
    app:
        container_name: passwordless-app
        build:
            context: .
            args:
                UID: ${UID}
                GID: ${GID}
                USER: ${USER}
        depends_on:
            - database
        env_file:
            - .env
        ports:
            - 42069:5173
        tty: true
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
        networks:
            - default
            - external

    web:
        container_name: passwordless-web
        image: nginx:stable-alpine
        depends_on:
            - app
        ports:
            - 80
        environment:
            - VIRTUAL_HOST=passwordless.localhost
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - default
            - external

    database:
        container_name: passwordless-db
        image: postgres:16-alpine
        ports:
            - 54321:5432
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=user
            - POSTGRES_DB=passwordless
        volumes:
            - passwordless_data:/var/lib/postgresql/data
        networks:
            - default
            - external

volumes:
    passwordless_data:

networks:
    default:
    external:
        external: true
        name: ${DOCKER_EXTERNAL_NETWORK}
